### ISSUE TITLE
cy.getTemporaryEmail is not a function

### ISSUE THREAD

**Issue by jgonzalezalbisu** [e23thr/cypress-guerrillamail#3]
I'm seeing this error when trying the function cy.getTemporaryEmail with the following code:
```
		cy.origin("https://www.guerrillamail.com", function () {
			cy.getTemporaryEmail().as("@randomEmail");
		});
```

![image](https://github.com/e23thr/cypress-guerrillamail/assets/23585745/66ae24e6-ec4b-479d-ac70-5b3d1aae3974)

**Comment by zlesak** [comment]
Hi there! I ran into the same problem, even after enabling `experimentalOriginDependencies: true` and importing in `e2e.js` . As I saw some similar problem at other issue threads I came to a 'solution'. As you get the email address mostly once before all set of tests, I put the `cy.origin` block into before hook. Also, the important part, was to add `Cypress.require('cypress-guerrillamail');` as a part of the `cy.origin` block. After that, you, as me, may have the same next problem with unknown wait until error. You may solve it by installing `npm i -D cypress-wait-until`, and importing it in `e2e.js` file, and also, as before, importing it in the `cy.origin` block with `Cypress.require('cypress-wait-until');`. I hope this works for you.

**Comment by priyankvadaliya753** [comment]
> Cypress.require('cypress-wait-until')

Perfectly working Thanks @zlesak 

<img width="663" alt="image" src="https://github.com/e23thr/cypress-guerrillamail/assets/82139164/c9a74952-16bc-44f0-9841-77dcf669bb36">

**Comment by e23thr** [comment]
Just update a new version (0.0.4) with dependencies update and README update

Thanks
